### ISSUE TITLE
Keenan's recommended changes

### ISSUE THREAD

**Issue by jgoeders** [byu-cpe/y-badge#14]
* [ ] Add a brief explanation to the section on cloning the repository as to what that means
Flip the order of the cloning options so that cloning from GUI comes before cloning from terminal
* [ ] Add a brief explanation of how the src code is organized so they know where write their code
* [ ] Add a few reminders to the LED module to help them remember how to upload their code without having to go back to the tutorial page.
* [ ] Reminder to comment and uncomment code to switch between exploration and challenge methods
* [ ] Change the numbering of the challenges so that they look discrete instead of like sequential steps (sub headers or bold “Challenge 1” etc instead)
* [ ] Slow down the delay on the yellow light example in the delays section so that it turns off more slowly and is easier to observe
* [ ] Explain the difference between a method call and declaration, including return types so that we don’t have people commenting out declarations or signatures and getting errors.

**Comment by KeenanRileyFaulkner** [comment]
New pr open that addresses all of the above

**Comment by jgoeders** [comment]
Fixed
