### ISSUE TITLE
Hint spacing

### ISSUE THREAD

**Issue by jgoeders** [byu-cpe/y-badge#21]
@KeenanRileyFaulkner 

Is it easy to fix the spacing here?  The hint seems to be closer to the next item:

<img width="891" alt="image" src="https://github.com/byu-cpe/y-badge/assets/1851142/38531286-e764-4f2d-b7c6-3dfcfe20da6f">

**Comment by KeenanRileyFaulkner** [comment]
I noticed that. My best guess is that it would be an inline style, attribute, or bootstrap class on the details tag. I'll take a look in a bit.

**Comment by jgoeders** [comment]
Fixed by #22
